### ISSUE TITLE
Can support Kaspersky cloud scanning function

### ISSUE THREAD

**Issue by 8MiYile** [djdefi/gitavscan#84]
https://opentip.kaspersky.com/
If possible, I would like to be able to upload the compiled results to Kaspersky Scan and have an exclamation point message pop up in Actions containing a link to the scan results
and the feature is only available with this issue https://github.com/djdefi/gitavscan/issues/20

**Comment by djdefi** [comment]
I think this would be something you could accomplish in a follow up step of an Actions workflow, or separate dependant workflow.

I'm not sure about opentip, but VirusTotal has an API that allows uploading files for analysis: https://docs.virustotal.com/reference/files-scan

You could detect suspected malware with the `gitavscan` Action, and then post them to that API for example.

#20 is now resolved, so I am going to close this as not planned since it is a bit out of scope for this specific Action.
